### ISSUE TITLE
ERROR 12: bad packet length  - when trying to view a song repo

### ISSUE THREAD

**Issue by Catsvilles** [petersalomonsen/githttpserver#22]
Hi, Peter! I wanted to try and play with this song here https://youtu.be/Hko5ZXxulaY and realized it's stored in your other Git WASM project so I got into learning and researching how all this works and tried to view the song in the music studio but unfortunately, it works neither in the studio and not in the stand alone git app too (this is the [url](https://wasm-git.petersalomonsen.com/psalomo202101) I try to Clone) for me and I'm getting the error in the title. Am I doing something wrong or the files are deleted / moved to a different URL?

**Comment by petersalomonsen** [comment]
It's just a permission thing. I've opened up now so that the repo is accessible for reading/cloning to everyone now, even when not being logged in.

Please try again, and let me know if it works for you :)

**Comment by Catsvilles** [comment]
Thank you, works perfectly! Now I'm getting more seriously into learning how to compose music and do DSP with the WASM studio you've created! :) Also, I plan to port a cool Reverb to AS, so hopefully I can PR to main repo as soon as I will figure it out :)

**Comment by petersalomonsen** [comment]
Cool Reverb would be awesome ! Looking forward to it, and also to hear what you will create with the Wasm studio :)
